version: '2'

services:
    prometheus:
        container_name: emprometheus
        build: PrometheusMonitoring/server/.
        ports:
            - "9090:9090"
        volumes:
            - to_monitor:/home/to_monitor
    grafana:
        container_name: grafana
        image: grafana/grafana
        ports:
            - "3000:3000"
        depends_on:
            - prometheus
        volumes:
            - ./Grafana/:/etc/grafana/provisioning/
    ionixmon:
        container_name: ionixmon
        build: PrometheusMonitoring/devicemonitor/ionixmon/.
        ports:
            - "8060:8060"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    to_monitor: